# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: [ "**" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: /kitchen-sink-server/kitchen-sink-server # GitHub actions duplicate project name
      DB_URL: ":memory:"
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Download Go Migrate
      run: curl -L https://github.com/golang-migrate/migrate/releases/download/$version/migrate.$os-$arch.tar.gz | tar xvz

    - name: Test Migration Script
      run: make migrate-up
